# NUMPY INTRODUTION 
* This is numerical python and it is used for scientific computing. 
* np = syntax 
* Can be used for linear algebra as well as random number capability. 
* Numpy array - a N-dimensional forms of rows and columns, more powerful than lists. fast, convenient 
* an array is a list in other languages 

In [3]:
import numpy as np 

In [ ]:
# np. - an object of a particular class 

In [1]:
# single dimensional 
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# multi-dimensional 
a = np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
# x = '' = means that its not empty and a memory has been allocated. 
# none values better to represent them with 0 

In [6]:
ls1 = [[1,3,5],[4,9,7],[9,9,4]]
ls1

[[1, 3, 5], [4, 9, 7], [9, 9, 4]]

In [16]:
ls = [4,5,6,7,5,9]
arr1 = np.array(ls)
arr1

array([4, 5, 6, 7, 5, 9])

In [13]:
arr1.sort()

In [5]:
arr1

NameError: name 'arr1' is not defined

In [17]:
len(ls)

6

In [18]:
len(arr1)

6

In [19]:
# sum of all values 
x = sum(ls)

In [20]:
x

36

In [24]:
y = sum(arr1)
y

36

In [2]:
from statistics  import mean 

In [4]:
ls = [4,5,6,7,5,9]
arr1 = np.array(ls)
arr1

NameError: name 'np' is not defined

In [5]:
import numpy as np

In [6]:
ls = [4,5,6,7,4,5]
arr1 = np.array(ls)
arr1

array([4, 5, 6, 7, 4, 5])

In [11]:
from statistics import mean 
ml = mean(ls)
ml

5.166666666666667

In [13]:
al = arr1.mean()
al

5.166666666666667

In [14]:
arr1

array([4, 5, 6, 7, 4, 5])

In [15]:
arr1.ndim

1

## Multidimensional array 

In [55]:
ls2 = [[23,45,67,456,334,90],[45,66,777,45,99,9],[334,56,77,54,3,83]]
ls2

[[23, 45, 67, 456, 334, 90],
 [45, 66, 777, 45, 99, 9],
 [334, 56, 77, 54, 3, 83]]

In [ ]:
# instead of writing none. represent it with np.nan can be multiple
# = nan is not a number 
# when you check for shape = .shape it will be a matrix 
# when you run for dtype = float because of the np.nan
# floats more data than an int 

In [50]:
print(ls2[-2][-4])

777


In [56]:
arr2 = np.array(ls2)
arr2

array([[ 23,  45,  67, 456, 334,  90],
       [ 45,  66, 777,  45,  99,   9],
       [334,  56,  77,  54,   3,  83]])

In [57]:
arr2.shape

(3, 6)

In [49]:
arr2.dtype

dtype('int32')

In [36]:
arr2.ndim

2

In [67]:
# .copy create a new array
# arr4 = arr2
# arr4

array([[ 23,  45,  67, 456, 334,  90],
       [ 45,  66, 777,  45,  99,   9],
       [334,  56,  77,  54,   3,  83]])

In [72]:
arr2m= arr2.mean()

In [76]:
ls3 = [[23,45,67,456,334,90],[45,66,777,45,99,9],[334,56,77,54,3,83]]
ls3

[[23, 45, 67, 456, 334, 90],
 [45, 66, 777, 45, 99, 9],
 [334, 56, 77, 54, 3, 83]]

In [77]:
arr3 = np.array(ls3)

In [78]:
arr3

array([[ 23,  45,  67, 456, 334,  90],
       [ 45,  66, 777,  45,  99,   9],
       [334,  56,  77,  54,   3,  83]])

In [79]:
arr3m = arr3.mean()
arr3m

147.94444444444446

In [80]:
arr3.shape

(3, 6)

In [108]:
# finding mean using axis
m1 = np.nanmean(arr3, axis=1)
m1

array([169.16666667, 173.5       , 101.16666667])

In [81]:
ls4 = [[23,45,np.nan,456,334,np.nan],[45,np.nan,777,np.nan,99,9],[np.nan,56,77,54,3,83]]
ls4

[[23, 45, nan, 456, 334, nan],
 [45, nan, 777, nan, 99, 9],
 [nan, 56, 77, 54, 3, 83]]

In [82]:
arr4 = np.array(ls4)

In [83]:
arr4

array([[ 23.,  45.,  nan, 456., 334.,  nan],
       [ 45.,  nan, 777.,  nan,  99.,   9.],
       [ nan,  56.,  77.,  54.,   3.,  83.]])

In [85]:
arr4.dtype

dtype('float64')

In [106]:
arr4.shape

()

In [84]:
# finding the mean 
arr4m = arr4.mean()
arr4m

nan

In [86]:
arr4m = np.nanmean(arr4)

In [88]:
arr4m

158.53846153846155

In [89]:
# finding the max 
arr4max = np.nanmax(arr4)

In [94]:
arr4max

777.0

In [101]:
# finding the min 
arr4min = np.nanmin(arr4)

In [97]:
arr4min

3.0

In [120]:
arr4

3.0

In [121]:
arr4 = np.array(ls4)

In [122]:
arr4

array([[ 23.,  45.,  nan, 456., 334.,  nan],
       [ 45.,  nan, 777.,  nan,  99.,   9.],
       [ nan,  56.,  77.,  54.,   3.,  83.]])

In [123]:
arr4

array([[ 23.,  45.,  nan, 456., 334.,  nan],
       [ 45.,  nan, 777.,  nan,  99.,   9.],
       [ nan,  56.,  77.,  54.,   3.,  83.]])

In [124]:
# .isnan = is not a number
np.isnan(arr4)

array([[False, False,  True, False, False,  True],
       [False,  True, False,  True, False, False],
       [ True, False, False, False, False, False]])

In [128]:
arrlog = np.isnan(arr4)
arrlog

array([[False, False,  True, False, False,  True],
       [False,  True, False,  True, False, False],
       [ True, False, False, False, False, False]])

In [129]:
# replacing a nan with a number 
arr4[arrlog] = 8
arr4

array([[ 23.,  45.,   8., 456., 334.,   8.],
       [ 45.,   8., 777.,   8.,  99.,   9.],
       [  8.,  56.,  77.,  54.,   3.,  83.]])

In [131]:
# creating a new variable 
# as 4 changes so does 5 
arr5 = arr4
arr5

array([[ 23.,  45.,   8., 456., 334.,   8.],
       [ 45.,   8., 777.,   8.,  99.,   9.],
       [  8.,  56.,  77.,  54.,   3.,  83.]])

In [132]:
print(type(arr4))

<class 'numpy.ndarray'>


In [133]:
print(type(arr5))

<class 'numpy.ndarray'>


In [135]:
# coppy = so when you change 4, 6 wont change 
arr6 = arr4.copy
arr6

<function ndarray.copy>

# TASK 

In [147]:
a1 = np.array([(17,12,np.nan,3),(30,np.nan,44,59),(78,34,98,12),(22,np.nan,78,np.nan)])


In [148]:
a1

array([[17., 12., nan,  3.],
       [30., nan, 44., 59.],
       [78., 34., 98., 12.],
       [22., nan, 78., nan]])

In [152]:
# replace np.nan with zeros 
arrx = np.nan_to_num (a1)
arrx

array([[17., 12.,  0.,  3.],
       [30.,  0., 44., 59.],
       [78., 34., 98., 12.],
       [22.,  0., 78.,  0.]])

In [145]:
# replace the np.nan with the mean of the array 

In [151]:
a2 = np.array([(17,12,np.nan,3),(30,np.nan,44,59),(78,34,98,12),(22,np.nan,78,np.nan)])
a2

array([[17., 12., nan,  3.],
       [30., nan, 44., 59.],
       [78., 34., 98., 12.],
       [22., nan, 78., nan]])

In [153]:
arrym = np.nanmean(a2)
arrym

40.583333333333336

In [161]:
ay = np.nan_to_num(np.nanmean


<function numpy.nanmean(a, axis=None, dtype=None, out=None, keepdims=<no value>)>