# BASIC PYTHON PRACTICE 

In [87]:
even = []
start , end = 20, 100
comp_even = [num for num in range (start, end+1)  if num %2 == 0]
print(comp_even)

[20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [88]:
odd = []
start, end = 10, 20
comp_odd = [num for num in range (start, end +1)  if num %2 != 0]
print(comp_odd)

[11, 13, 15, 17, 19]


In [89]:
even1 = {}
start = 5 
end = 60 
comp_even1 = {str(num): num for num in range (start, end+1)  if num % 2 == 0}
print(comp_even1)

{'6': 6, '8': 8, '10': 10, '12': 12, '14': 14, '16': 16, '18': 18, '20': 20, '22': 22, '24': 24, '26': 26, '28': 28, '30': 30, '32': 32, '34': 34, '36': 36, '38': 38, '40': 40, '42': 42, '44': 44, '46': 46, '48': 48, '50': 50, '52': 52, '54': 54, '56': 56, '58': 58, '60': 60}


In [90]:
odd1 = {}
start = 8 
end = 1001
comp_odd1 = {str(num): num for num in range (start,end+1)  if num % 2 != 0}
comp_odd1

{'9': 9,
 '11': 11,
 '13': 13,
 '15': 15,
 '17': 17,
 '19': 19,
 '21': 21,
 '23': 23,
 '25': 25,
 '27': 27,
 '29': 29,
 '31': 31,
 '33': 33,
 '35': 35,
 '37': 37,
 '39': 39,
 '41': 41,
 '43': 43,
 '45': 45,
 '47': 47,
 '49': 49,
 '51': 51,
 '53': 53,
 '55': 55,
 '57': 57,
 '59': 59,
 '61': 61,
 '63': 63,
 '65': 65,
 '67': 67,
 '69': 69,
 '71': 71,
 '73': 73,
 '75': 75,
 '77': 77,
 '79': 79,
 '81': 81,
 '83': 83,
 '85': 85,
 '87': 87,
 '89': 89,
 '91': 91,
 '93': 93,
 '95': 95,
 '97': 97,
 '99': 99,
 '101': 101,
 '103': 103,
 '105': 105,
 '107': 107,
 '109': 109,
 '111': 111,
 '113': 113,
 '115': 115,
 '117': 117,
 '119': 119,
 '121': 121,
 '123': 123,
 '125': 125,
 '127': 127,
 '129': 129,
 '131': 131,
 '133': 133,
 '135': 135,
 '137': 137,
 '139': 139,
 '141': 141,
 '143': 143,
 '145': 145,
 '147': 147,
 '149': 149,
 '151': 151,
 '153': 153,
 '155': 155,
 '157': 157,
 '159': 159,
 '161': 161,
 '163': 163,
 '165': 165,
 '167': 167,
 '169': 169,
 '171': 171,
 '173': 173,
 '175': 175,
 '

In [91]:
print(comp_even1['6'])

6


In [92]:
color = ['red', 'yellow', 'blue']
objects = ['shoes', 'house', 'books']
colored_objects = [ (x,y) for x in color for y in objects]
print(colored_objects)

[('red', 'shoes'), ('red', 'house'), ('red', 'books'), ('yellow', 'shoes'), ('yellow', 'house'), ('yellow', 'books'), ('blue', 'shoes'), ('blue', 'house'), ('blue', 'books')]


# NUMPY PYTHON PRACTICE 

In [93]:
import numpy as np

In [94]:
a = np.array([1,2,4,5,6,6,7])
a

array([1, 2, 4, 5, 6, 6, 7])

In [95]:
b = np.array ([(45,6,6,5,3), (7,7,76)])
b

array([(45, 6, 6, 5, 3), (7, 7, 76)], dtype=object)

In [96]:
b1 = np.array([(1,2,3), (2,3,2), (4,4,3)])
b1

array([[1, 2, 3],
       [2, 3, 2],
       [4, 4, 3]])

In [97]:
a1 = [2,4,36,7,5,7,44,5,4,44]
a1

[2, 4, 36, 7, 5, 7, 44, 5, 4, 44]

In [98]:
arr1 = np.array(a1)

In [99]:
arr1

array([ 2,  4, 36,  7,  5,  7, 44,  5,  4, 44])

In [100]:
a2 = (2,2,3,3,2,3)
a2

(2, 2, 3, 3, 2, 3)

In [101]:
arr2 = np.array(a2)

In [102]:
arr2

array([2, 2, 3, 3, 2, 3])

In [103]:
from statistics import mean

In [104]:
arr2m = arr2.mean()
arr2m 

2.5

In [105]:
arr1m = arr1.mean()
arr1m 

15.8

In [106]:
arr2.ndim

1

In [107]:
arr2.ndim

1

In [108]:
a3 = [[2,2,2,3],[2,3,3,4],[5,6,5,6]]
a3

[[2, 2, 2, 3], [2, 3, 3, 4], [5, 6, 5, 6]]

In [109]:
type(a3)

list

In [110]:
arr3 = np.array(a3)

In [111]:
arr3

array([[2, 2, 2, 3],
       [2, 3, 3, 4],
       [5, 6, 5, 6]])

In [112]:
print(a3[-2][-4])

2


In [113]:
arr3.shape

(3, 4)

In [114]:
arr3.ndim

2

In [115]:
arr3.dtype

dtype('int32')

In [116]:
arr3m = arr3.mean()
arr3m

3.5833333333333335

In [117]:
arr3

array([[2, 2, 2, 3],
       [2, 3, 3, 4],
       [5, 6, 5, 6]])

In [118]:
a4 = [[2,4,5,np.nan], [np.nan, np.nan, 6,5], [4,5,np.nan,6]]
a4

[[2, 4, 5, nan], [nan, nan, 6, 5], [4, 5, nan, 6]]

In [119]:
type(a4)

list

In [120]:
arr4 = np.array(a4)
arr4

array([[ 2.,  4.,  5., nan],
       [nan, nan,  6.,  5.],
       [ 4.,  5., nan,  6.]])

In [121]:
arr4.shape

(3, 4)

In [122]:
arr4m = arr4.mean()
arr4m

nan

In [123]:
arr4m = np.nanmean(arr4)
arr4m

4.625

In [124]:
np.isnan(arr4)

array([[False, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [125]:
arr4max = np.nanmax(arr4)
arr4max

6.0

In [126]:
arr4x = np.nan_to_num(arr4)

In [127]:
arr4x

array([[2., 4., 5., 0.],
       [0., 0., 6., 5.],
       [4., 5., 0., 6.]])

In [128]:
arr4xm = arr4x.mean()
arr4xm

3.0833333333333335

# PANDAS PYTHON PRACTICE

In [129]:
import pandas as pd 

In [134]:
data = {"books" : [2,4,3,5,3], "shoes" : [3,5,8,8,9], "pens" : [2,3,3,3,3], "bags" : [6,5,5,5,4]}
data

{'books': [2, 4, 3, 5, 3],
 'shoes': [3, 5, 8, 8, 9],
 'pens': [2, 3, 3, 3, 3],
 'bags': [6, 5, 5, 5, 4]}

In [132]:
df_data = pd.DataFrame(data)

In [133]:
df_data

books  shoes  pens  bags
0      2      3     2     6
1      4      5     3     5
2      3      8     3     5
3      5      8     3     5
4      3      9     3     4

In [135]:
type(df_data)

pandas.core.frame.DataFrame

In [136]:
df_data = pd.DataFrame(data, index=["Molly", "Lilly", "Sally", "Donald", "Mark"])
df_data

books  shoes  pens  bags
Molly       2      3     2     6
Lilly       4      5     3     5
Sally       3      8     3     5
Donald      5      8     3     5
Mark        3      9     3     4

In [137]:
type(df_data)

pandas.core.frame.DataFrame

In [139]:
a = df_data["books"]
a

Molly     2
Lilly     4
Sally     3
Donald    5
Mark      3
Name: books, dtype: int64

In [140]:
type(a)

pandas.core.series.Series

In [142]:
df_data.columns

Index(['books', 'shoes', 'pens', 'bags'], dtype='object')

In [144]:
c = df_data.columns
c[0]

'books'

In [145]:
c[-2]

'pens'

In [148]:
df_data.rename({"books":"pencils", "shoes":"bags", "pens":"colorpencils", "bags": "rulers"}, axis='columns')

pencils  bags  colorpencils  rulers
Molly         2     3             2       6
Lilly         4     5             3       5
Sally         3     8             3       5
Donald        5     8             3       5
Mark          3     9             3       4

In [156]:
# THIS WORKS WITH THE ORIGIBAL INDEX, NOT THE CHANGES ONE AS SEEN ABOVE. 
df_data.loc["Molly", ["bags", "shoes"]]

bags     6
shoes    3
Name: Molly, dtype: int64

In [158]:
df_data.loc ["Donald", ["books", "bags"]]

books    5
bags     5
Name: Donald, dtype: int64

In [159]:
import numpy as np 

In [160]:
arrd = np.array(data)

In [161]:
arrd

array({'books': [2, 4, 3, 5, 3], 'shoes': [3, 5, 8, 8, 9], 'pens': [2, 3, 3, 3, 3], 'bags': [6, 5, 5, 5, 4]},
      dtype=object)

In [165]:
df_movies = pd.read_csv("data/imdb_data_1000.csv")

In [166]:
df_movies

Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1       2               Prometheus  Adventure,Mystery,Sci-Fi   
2       3                    Split           Horror,Thriller   
3       4                     Sing   Animation,Comedy,Family   
4       5            Suicide Squad  Action,Adventure,Fantasy   
..    ...                      ...                       ...   
995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996   997          Hostel: Part II                    Horror   
997   998   Step Up 2: The Streets       Drama,Music,Romance   
998   999             Search Party          Adventure,Comedy   
999  1000               Nine Lives     Comedy,Family,Fantasy   

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley Scott   
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4    A secret government agency recruits some of th...            David Ayer   
..                                                 ...                   ...   
995  A tight-knit team of rising investigators, alo...             Billy Ray   
996  Three American college students studying abroa...              Eli Roth   
997  Romantic sparks occur between two dance studen...            Jon M. Chu   
998  A pair of friends embark on a mission to reuni...        Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld   

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014   
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012   
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016   
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016   
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016   
..                                                 ...   ...   
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015   
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007   
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008   
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  
0                  121     8.1  757074              333.13       76.0  
1                  124     7.0  485820              126.46       65.0  
2                  117     7.3  157606              138.12       62.0  
3                  108     7.2   60545              270.32       59.0  
4                  123     6.2  393727              325.02       40.0  
..                 ...     ...     ...                 ...        ...  
995                111     6.2   27585                 NaN       45.0  
996                 94     5.5   73152               17.54       46.0  
997                 98     6.2   70699               58.01       50.0  
998                 93     5.6    4881                 NaN       22.0  
999                 87     5.3   12435               19.64       11.0  

[1000 rows x 12 columns]

In [167]:
df_movies.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [175]:
df_movies.loc[0]

Rank                                                                  1
Title                                           Guardians of the Galaxy
Genre                                           Action,Adventure,Sci-Fi
Description           A group of intergalactic criminals are forced ...
Director                                                     James Gunn
Actors                Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Year                                                               2014
Runtime (Minutes)                                                   121
Rating                                                              8.1
Votes                                                            757074
Revenue (Millions)                                               333.13
Metascore                                                            76
Name: 0, dtype: object

In [176]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                1000 non-null   int64  
 1   Title               1000 non-null   object 
 2   Genre               1000 non-null   object 
 3   Description         1000 non-null   object 
 4   Director            1000 non-null   object 
 5   Actors              1000 non-null   object 
 6   Year                1000 non-null   int64  
 7   Runtime (Minutes)   1000 non-null   int64  
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64  
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB


In [177]:
df_movies.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [185]:
df_movies_one = df_movies.copy()

In [205]:
df_movies_one.rename(columns = {"Runtime (Minutes)": "Runtime_minutes", "Revenue (Millions)": "Revenue_millions"}, inplace=True )

In [207]:
df_movies_one.head(1)

Rank                    Title                    Genre  \
0     1  Guardians of the Galaxy  Action,Adventure,Sci-Fi   

                                         Description    Director  \
0  A group of intergalactic criminals are forced ...  James Gunn   

                                              Actors  Year  Runtime_minutes  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014              121   

   Rating   Votes  Revenue_millions  Metascore  
0     8.1  757074            333.13       76.0

In [211]:
df_movies_one.columns =  [c.lower() for c in df_movies_one.columns]

In [212]:
df_movies_one.columns

Index(['rank', 'title', 'genre', 'description', 'director', 'actors', 'year',
       'runtime_minutes', 'rating', 'votes', 'revenue_millions', 'metascore'],
      dtype='object')

In [215]:
df_movies_one.columns = [c.upper() for c in df_movies_one.columns]

In [216]:
df_movies_one.columns

Index(['RANK', 'TITLE', 'GENRE', 'DESCRIPTION', 'DIRECTOR', 'ACTORS', 'YEAR',
       'RUNTIME_MINUTES', 'RATING', 'VOTES', 'REVENUE_MILLIONS', 'METASCORE'],
      dtype='object')

In [217]:
df_movies_one.shape

(1000, 12)

In [218]:
df_movies_one.drop_duplicates()

RANK                    TITLE                     GENRE  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1       2               Prometheus  Adventure,Mystery,Sci-Fi   
2       3                    Split           Horror,Thriller   
3       4                     Sing   Animation,Comedy,Family   
4       5            Suicide Squad  Action,Adventure,Fantasy   
..    ...                      ...                       ...   
995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996   997          Hostel: Part II                    Horror   
997   998   Step Up 2: The Streets       Drama,Music,Romance   
998   999             Search Party          Adventure,Comedy   
999  1000               Nine Lives     Comedy,Family,Fantasy   

                                           DESCRIPTION              DIRECTOR  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley Scott   
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4    A secret government agency recruits some of th...            David Ayer   
..                                                 ...                   ...   
995  A tight-knit team of rising investigators, alo...             Billy Ray   
996  Three American college students studying abroa...              Eli Roth   
997  Romantic sparks occur between two dance studen...            Jon M. Chu   
998  A pair of friends embark on a mission to reuni...        Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld   

                                                ACTORS  YEAR  RUNTIME_MINUTES  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014              121   
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012              124   
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016              117   
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016              108   
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016              123   
..                                                 ...   ...              ...   
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015              111   
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007               94   
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008               98   
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014               93   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016               87   

     RATING   VOTES  REVENUE_MILLIONS  METASCORE  
0       8.1  757074            333.13       76.0  
1       7.0  485820            126.46       65.0  
2       7.3  157606            138.12       62.0  
3       7.2   60545            270.32       59.0  
4       6.2  393727            325.02       40.0  
..      ...     ...               ...        ...  
995     6.2   27585               NaN       45.0  
996     5.5   73152             17.54       46.0  
997     6.2   70699             58.01       50.0  
998     5.6    4881               NaN       22.0  
999     5.3   12435             19.64       11.0  

[1000 rows x 12 columns]

In [219]:
df_movies_one.shape

(1000, 12)

In [220]:
df_movies_one.drop_duplicates(keep = False, inplace = True)

In [221]:
df_movies_one.shape

(1000, 12)

In [223]:
df_movies_one.drop_duplicates(inplace = True, keep = "last")

In [224]:
df_movies_one.shape

(1000, 12)

In [249]:
temp_df = df_movies_one.append(df_movies_one)

In [250]:
temp_df.shape

(2000, 12)

In [251]:
temp_df =temp_df.append(df_movies_one)

In [252]:
temp_df.shape

(3000, 12)

In [253]:
temp_df_one = temp_df.copy()

In [254]:
temp_df_one.shape

(3000, 12)

In [261]:
temp_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   RANK              1000 non-null   int64  
 1   TITLE             1000 non-null   object 
 2   GENRE             1000 non-null   object 
 3   DESCRIPTION       1000 non-null   object 
 4   DIRECTOR          1000 non-null   object 
 5   ACTORS            1000 non-null   object 
 6   YEAR              1000 non-null   int64  
 7   RUNTIME_MINUTES   1000 non-null   int64  
 8   RATING            1000 non-null   float64
 9   VOTES             1000 non-null   int64  
 10  REVENUE_MILLIONS  872 non-null    float64
 11  METASCORE         936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 101.6+ KB


In [262]:
temp_df.drop_duplicates(inplace = True, keep = "first")

In [263]:
temp_df.shape

(1000, 12)

In [264]:
temp_df_one.drop_duplicates(keep = 'last', inplace = True)

In [265]:
temp_df_one.shape

(1000, 12)

In [266]:
temp_df_one.drop_duplicates(inplace = True, keep = False)

In [267]:
temp_df_one.shape

(1000, 12)

In [268]:
df_movies_one.shape

(1000, 12)

In [269]:
df_movies.shape

(1000, 12)

In [270]:
df_comb = df_movies_one.append(df_movies)

In [272]:
df_comb.shape

(2000, 24)

In [273]:
df_movies_one.columns

Index(['RANK', 'TITLE', 'GENRE', 'DESCRIPTION', 'DIRECTOR', 'ACTORS', 'YEAR',
       'RUNTIME_MINUTES', 'RATING', 'VOTES', 'REVENUE_MILLIONS', 'METASCORE'],
      dtype='object')

In [274]:
df_movies.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [275]:
df_comb.columns

Index(['RANK', 'TITLE', 'GENRE', 'DESCRIPTION', 'DIRECTOR', 'ACTORS', 'YEAR',
       'RUNTIME_MINUTES', 'RATING', 'VOTES', 'REVENUE_MILLIONS', 'METASCORE',
       'Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [276]:
df_movies_one.isnull()

RANK  TITLE  GENRE  DESCRIPTION  DIRECTOR  ACTORS   YEAR  \
0    False  False  False        False     False   False  False   
1    False  False  False        False     False   False  False   
2    False  False  False        False     False   False  False   
3    False  False  False        False     False   False  False   
4    False  False  False        False     False   False  False   
..     ...    ...    ...          ...       ...     ...    ...   
995  False  False  False        False     False   False  False   
996  False  False  False        False     False   False  False   
997  False  False  False        False     False   False  False   
998  False  False  False        False     False   False  False   
999  False  False  False        False     False   False  False   

     RUNTIME_MINUTES  RATING  VOTES  REVENUE_MILLIONS  METASCORE  
0              False   False  False             False      False  
1              False   False  False             False      False  
2              False   False  False             False      False  
3              False   False  False             False      False  
4              False   False  False             False      False  
..               ...     ...    ...               ...        ...  
995            False   False  False              True      False  
996            False   False  False             False      False  
997            False   False  False             False      False  
998            False   False  False              True      False  
999            False   False  False             False      False  

[1000 rows x 12 columns]

In [278]:
df_movies_nulls = df_movies_one.isnull()

In [279]:
df_movies_nulls.sum()

RANK                  0
TITLE                 0
GENRE                 0
DESCRIPTION           0
DIRECTOR              0
ACTORS                0
YEAR                  0
RUNTIME_MINUTES       0
RATING                0
VOTES                 0
REVENUE_MILLIONS    128
METASCORE            64
dtype: int64

In [280]:
df_movies_one1 = df_movies_one.dropna()

In [282]:
df_movies_one1.shape

(838, 12)

In [ ]:
revenue =